Domsdatabasen API
alexandrainst/alexandra_ai_data pull request #5
Opened 2024-07-11 09:48 UTC by oliverkinch

Example usage

```
from alexandra_ai_data.domsdatabasen import Domsdatabasen

domsdatabasen = Domsdatabasen()

case = domsdatabasen.get_case(case_id="100")

print(case)

```

2024-07-15 13:09 UTC, saattrupdan requested changes
Looks great! 🎉 

I've only got a few suggestions.

Also, I added a PR to merge in with your branch, which just updates the dependencies, Github workflows and such, since we haven't updated the repo in some time. No changes to your code in that PR, so it would be great if you could review that PR into this branch as well.

2024-07-15 13:09 UTC, saattrupdan commented on src/alexandra_ai_data/domsdatabasen.py
> +        self.dataset = load_dataset("alexandrainst/domsdatabasen")["train"]
Consider using the `split` argument instead:

```suggestion
        self.dataset = load_dataset("alexandrainst/domsdatabasen", split="train")
```

2024-07-15 13:09 UTC, saattrupdan commented on src/alexandra_ai_data/domsdatabasen.py
> +            case_id = str(case_id)
If integer inputs are allowed, then this should be stated in the type signature.

2024-07-15 13:09 UTC, saattrupdan commented on src/alexandra_ai_data/domsdatabasen.py
> +    def _initialze_objects(self):
Typo:

```suggestion
    def _initialize_objects(self):
```

2024-07-15 13:09 UTC, saattrupdan commented on src/alexandra_ai_data/domsdatabasen.py
> +        self._initialze_objects()
Typo:

```suggestion
        self._initialize_objects()
```

2024-07-15 13:09 UTC, saattrupdan commented on src/scripts/domsdatabasen_example_usage.py
> +print(case)
Consider moving these kinds of examples to a separate `examples` directory, in the root folder.

Alternatively, you could simply add this bit of code to the readme under the Quick Start section.

2024-07-17 08:58 UTC, oliverkinch commented
I have merged your PR and made commits w.r.t your requested changes @saattrupdan

2024-07-17 09:10 UTC, saattrupdan approved these changes
Looks great! Just a small typo that was my mistake 🙂

2024-07-17 09:10 UTC, saattrupdan commented on makefile
> -	@echo "Installed the 'ScandEval' project."
Whoops, I missed this bit. Could you rename "ScandEval" to "AlexandraAI-data" the two places in `make install`?

2024-07-17 12:25 UTC, oliverkinch commented on makefile
> -	@echo "Installed the 'ScandEval' project."
Done [a87d4b5](https://github.com/alexandrainst/alexandra_ai_data/pull/5/commits/a87d4b55230545d3364c1f2ed5d0295856eceec7)

2024-07-17 13:43 UTC, merged